# getAllBlogs
GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NGM0ZTY5ZjkxODBhYTVmMjgwYmI3NDgiLCJpYXQiOjE2OTEwNTU5NDZ9.HxHJlE_9iD7ullhslP87PJel6S-j4_p84fUrxaYSW7A

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Test title",
    "author": "DK",
    "url": "https://www.youtube.com",
    "likes": 1354
}


###

# create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "grzegorzb",
    "name": "Grzegorz Bażant",
    "password": "supersecretpassword"
}

###

# create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

###

# get all users
GET http://localhost:3003/api/users


###

# login
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}


###

#login2
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "grzegorzb",
    "password": "supersecretpassword"
}

###

# create new blog with jwt auth
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyemVnb3J6YiIsImlkIjoiNjRjNDFhYWNjNTE4MWE3OTkzOTJjYzY5IiwiaWF0IjoxNjkwODcxNDY1fQ.-Aua0q8UDmX0U_yFr15gLpqNVdGYbk3Z_FyBHXr9_ak

{
    "title": "grzblog",
    "author": "Mark Update",
    "url": "https://www.blogsToUpdate.com/test",
    "likes": 142
}

###

# delete blog
DELETE http://localhost:3003/api/blogs/64c41b69f93ef55bde65310c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NGM0MWFhZGM1MTgxYTc5OTM5MmNjNmQiLCJpYXQiOjE2OTA1NzM2NTF9.Qp4Fki-Hu30IZzQUt7TMgsmR7CtCI_RWnYswwIyDa-A

###

PUT http://localhost:3003/api/blogs/64c8a7c897504e01345433bb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyemVnb3J6YiIsImlkIjoiNjRjNDFhYWNjNTE4MWE3OTkzOTJjYzY5IiwiaWF0IjoxNjkwODcxNDY1fQ.-Aua0q8UDmX0U_yFr15gLpqNVdGYbk3Z_FyBHXr9_ak

{
    "user": "64c41aadc5181a799392cc6d",
    "title":"this is example how to steal blog from other authors",
    "author":"updated author",
    "url":"https://www.thisurldoesnotexist.com",
    "likes":8
}


###

# clear testing database
POST http://localhost:3003/api/testing/reset