# getAllBlogs
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Test title",
    "author": "DK",
    "url": "https://www.youtube.com",
    "likes": 1354
}


###

# create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "grzegorzb",
    "name": "Grzegorz Bażant",
    "password": "supersecretpassword"
}

###

# create new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

###

# get all users
GET http://localhost:3003/api/users
